// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJcdUPWo0gMkOVu-gJh-QC351tSJM4HLM',
    appId: '1:286565619611:web:73299ff35d42b61652b33e',
    messagingSenderId: '286565619611',
    projectId: 'evently-f7c3d',
    authDomain: 'evently-f7c3d.firebaseapp.com',
    storageBucket: 'evently-f7c3d.firebasestorage.app',
    measurementId: 'G-WXYZJEHKT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiG3p57OmZgfMOjKML9oHHuWzTRsOK3FE',
    appId: '1:286565619611:android:d293e39dae3e473652b33e',
    messagingSenderId: '286565619611',
    projectId: 'evently-f7c3d',
    storageBucket: 'evently-f7c3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw7CWKw7cG7s36_ONzQBGfXobqmbzULEY',
    appId: '1:286565619611:ios:a5dca9722d42e51652b33e',
    messagingSenderId: '286565619611',
    projectId: 'evently-f7c3d',
    storageBucket: 'evently-f7c3d.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw7CWKw7cG7s36_ONzQBGfXobqmbzULEY',
    appId: '1:286565619611:ios:a5dca9722d42e51652b33e',
    messagingSenderId: '286565619611',
    projectId: 'evently-f7c3d',
    storageBucket: 'evently-f7c3d.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJcdUPWo0gMkOVu-gJh-QC351tSJM4HLM',
    appId: '1:286565619611:web:a38169162ff930a552b33e',
    messagingSenderId: '286565619611',
    projectId: 'evently-f7c3d',
    authDomain: 'evently-f7c3d.firebaseapp.com',
    storageBucket: 'evently-f7c3d.firebasestorage.app',
    measurementId: 'G-NZ2P002DGP',
  );
}
